# Generated by Django 3.1.4 on 2021-09-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='costo',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
