# Generated by Django 3.1.4 on 2021-09-23 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Dosi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ndosis', models.IntegerField()),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animales.animal')),
                ('vacuna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vacunas.vacuna')),
            ],
        ),
    ]
