# Generated by Django 3.1.4 on 2021-09-23 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0001_initial'),
        ('inventarios', '0002_auto_20210922_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='animales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animales.animal'),
        ),
        migrations.AlterField(
            model_name='control',
            name='insumo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventarios.insumo'),
        ),
    ]
